// Custom edits -- these are edits that I manually checked
replace street = "CHURCH FIELD" if street == "CHURCHFIELDS" & postcode == "CB11 4BG"
replace street = "MILL MEADOW" if street == "DOLFELIN" & postcode == "CF33 4QA"
replace street = "GORDON ROAD" if locality == "MOORLAND WAY" & postcode == "C012 3TN"
replace street = "PATENOSTERS" if street == "PATERNOSTERS" & postcode == "GL20 5DX"
replace street = "CHAPEL STREET" if street == "OLD DRUM MEWS" & postcode == "GU32 3DP"
replace street = "ROYD HOUSE" if street == "ROYDHOUSE" & postcode == "HD7 5SB"
replace street = "DAVEY GARDENS" if street == "CHAVREY CLOSE" & postcode == "IG11 0FB"
replace street = "GOGMORE LANE" if street == "FOUNDRY MEWS" & postcode == "KT16 9AP"
replace street = "CARTWRIGHTS FARM ROAD" if street == "BRYONY MEWS" & postcode == "L24 1UY"
replace street = "DINARO CLOSE" if street == "COASTGUARD WALK" & postcode == "L25 3NR"
replace street = "PORTICO COURT" if locality == "MOSS HALL GROVE" & postcode == "L35 7LP"
replace street = "BELSFIELD COURT" if locality == "ROKER TERRACE" & postcode == "LA23 3EY"
replace street = "WINDSOR COURT" if locality == "BEL AIR CHALET ESTATE" & postcode == "LE16 7BL"
replace street = "ANGELL DRIVE" if street == "ALMONDSBURY CLOSE" & postcode == "LE16 9GJ"
replace street = "GLAN-Y-MOR" if street == "GLANYMOR" & postcode == "LL30 3NL"
replace street = "AWEL Y CASTELL" if street == "ASTON BANK" & postcode == "LL31 9GG"
